### ISSUE TITLE
Version '14.36.32532' is not valid; directory does not exist

### ISSUE THREAD

**Issue by akaszynski** [TheMrMilchmann/setup-msvc-dev#131]
When running https://github.com/danini/graph-cut-ransac/actions/runs/6111198852/job/16757364591 on https://github.com/danini/graph-cut-ransac, we're getting a failed build due to 14.36.32532 not existing. Not sure if there's a way around this since the installed version will be a moving target.

```
2023-09-13T14:32:02.8968085Z ##[group]Run TheMrMilchmann/setup-msvc-dev@v2.0.1
2023-09-13T14:32:02.8968584Z with:
2023-09-13T14:32:02.8968878Z   arch: x64
2023-09-13T14:32:02.8969105Z   toolset: 14.36.32532
2023-09-13T14:32:02.8969385Z ##[endgroup]
2023-09-13T14:32:05.4372356Z Normalized input arch to x64 (from x64)
2023-09-13T14:32:11.5725884Z ##[error]Invocation of vcvarsall.bat failed:
[ERROR:vcvars.bat] Version '14.36.32532' is not valid; directory does not exist
[ERROR:VsDevCmd.bat] *** VsDevCmd.bat encountered errors. Environment may be incomplete and/or incorrect. ***
[ERROR:VsDevCmd.bat] In an uninitialized command prompt, please 'set VSCMD_DEBUG=[value]' and then re-run
[ERROR:VsDevCmd.bat] vsdevcmd.bat [args] for additional details.
[ERROR:VsDevCmd.bat] Where [value] is:
[ERROR:VsDevCmd.bat]    1 : basic debug logging
[ERROR:VsDevCmd.bat]    2 : detailed debug logging
[ERROR:VsDevCmd.bat]    3 : trace level logging. Redirection of output to a file when using this level is recommended.
[ERROR:VsDevCmd.bat] Example: set VSCMD_DEBUG=3
[ERROR:VsDevCmd.bat]          vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
```

**Comment by akaszynski** [comment]
Strangely, when this step errored out, the rest of the build proceeded. I'd propose that when this step fails it raises and error and triggers the github workflow step to fail.

**Comment by TheMrMilchmann** [comment]
Hey @akaszynski, I looked into this and it looks like I was wrong.

> The error message indicates that the toolset version is correctly passed to the batch file. However, for some reason, the version cannot be found although 14.36.32532 is listed as an available toolset on all GitHub-hosted Windows runners.

`14.36.3253` is not listed as an available toolset but as an available runtime. The available compiler toolsets for windows-2022 runners can be found [in this table](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#workloads-components-and-extensions). They are the entries with the `Microsoft.VisualStudio.Component.VC.` prefix. The available versions for this runner OS are:

- `14.29` (`14.29.16.11`),
- `14.35` (`14.35.17.5`), and
- `14.37` (`14.37.17.7`).

**Comment by TheMrMilchmann** [comment]
The action is now properly marked as failed with [2.0.2](https://github.com/TheMrMilchmann/setup-msvc-dev/releases/tag/v2.0.2).
